echo "<form method='POST'>";
echo "<div class='ship-{$r->id} box' >" . PHP_EOL;
echo "<div class='id'>ID: $r->id</div>" . PHP_EOL;
echo "<input type='hidden' name='id' value='$r->id'>";
echo "<div class='manufacturer'>Manufacturer: $r->manufacturer</div>" . PHP_EOL;
echo "<div class='cost_in_credits'>Cost in credits: $r->cost_in_credits</div>" . PHP_EOL;
echo "<div class='length'>Length: $r->length</div>" . PHP_EOL;
echo "<div class='max_atmosphering_speed'>Max atmosphering speed: $r->max_atmosphering_speed</div>" . PHP_EOL;
echo "<div class='crew'>Crew: $r->crew</div>" . PHP_EOL;
echo "<div class='passengers'>Passengers: $r->passengers</div>" . PHP_EOL;
echo "<div class='cargo_capacity'>Cargo capacity: $r->cargo_capacity</div>" . PHP_EOL;
echo "<div class='consumables'>Consumables: $r->consumables</div>" . PHP_EOL;
echo "<div class='hyperdrive_rating'>Hyperdrive rating: $r->hyperdrive_rating</div>" . PHP_EOL;
echo "<div class='MGLT'>MGLT: $r->MGLT</div>" . PHP_EOL;
echo "<div class='starship_class'>Starship class: $r->starship_class</div>" . PHP_EOL;
echo '<label>' . "Number of ships: " . '</label>' . '<br>' . "<input type='number' min='0' name='nr_of_ships'>" . '<br>' . '<br>';
echo "<input type='submit' name='submit' value='Submit the form'/>";
echo '</form>';
echo '</div>';